---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.16

inputs:
  - name: dp-frontend-area-profiles-controller

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-frontend-area-profiles-controller/ci/scripts/build.sh
