---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-node-go
    tag: 1.19.4-rc.1

inputs:
  - name: dp-frontend-area-profiles

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-frontend-area-profiles/ci/scripts/build.sh
